# Generated by Django 5.0.6 on 2024-08-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuzzBox', '0006_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
